artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_file: dataset/SMSSpamCollection
  local_data_file: artifacts/data_ingestion/spam.csv

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  data_file: artifacts/data_ingestion/spam.csv

data_transformation:
  root_dir: artifacts/data_transformation
  input_data_file: artifacts/data_ingestion/spam.csv
  transformed_data_file: artifacts/data_transformation/spam_cleaned.csv

# ==========================================================
# Model Trainer
# ==========================================================

model_trainer:
  root_dir: artifacts/model_trainer

  input_data_file: artifacts/data_transformation/spam_cleaned.csv

  model_file: artifacts/model_trainer/spam_classifier.pkl

  vectorizer_file: artifacts/model_trainer/tfidf_vectorizer.pkl

# ==========================================================
# Model Evaluation
# ==========================================================

model_evaluation:
  root_dir: artifacts/model_evaluation

  input_data_file: artifacts/data_transformation/spam_cleaned.csv

  model_file: artifacts/model_trainer/spam_classifier.pkl

  vectorizer_file: artifacts/model_trainer/tfidf_vectorizer.pkl

  metric_file: artifacts/model_evaluation/metrics.json
